default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: test_project_main_development
  username: root
  password:
  host: localhost

test:
  <<: *default
  database: test_project_main_test
  username: root
  password:
  host: localhost

production:
  <<: *default
  url: <%= ENV['JAWSDB_URL'] %>